name: Pipeline notes project

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd notes_project
          pip install -r requirements.txt

      - name: Setup project configurartion
        run: |
          cd notes_project
          python manage.py collectstatic
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests with coverage
        run: |
          cd notes_project
          coverage run manage.py test
          coverage report

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ivanco93
          password: dockerhub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: notes_project/.
          push: true
          tags: ivanco93/andesgt-notes:latest

      - name: Logout from Docker Hub
        run: docker logout